// <auto-generated />
using Filmovi_projekt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filmovi_projekt.Migrations.Comments
{
    [DbContext(typeof(CommentsContext))]
    partial class CommentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Filmovi_projekt.Models.Comments", b =>
                {
                    b.Property<int>("id_comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_comment"));

                    b.Property<string>("change_date")
                        .IsRequired()
                        .HasColumnType("varchar(255) NULL");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("id_film")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<string>("insert_date")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_comment");

                    b.ToTable("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
